apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-example
spec:
  providerSpec:
    value: {}
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
    pods:
      cidrBlocks:
      - 192.169.0.0/16
    serviceDomain: "cluster.local"

