apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    server: https://localhost:8443
    insecure-skip-tls-verify: true
  name: kubeception
contexts:
- context:
    cluster: kubeception
    user: kubeception
  name: kubeception
current-context: kubeception
users:
- name: kubeception
  user:
    username: kubeception
    password: kubeception

