#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

VERSION=$(go list -m all | grep k8s.io/code-generator | rev | cut -d"-" -f1 | cut -d" " -f1 | rev)
TMP_DIR=$(mktemp -d)
git clone https://github.com/kubernetes/code-generator.git ${TMP_DIR}
(cd ${TMP_DIR} && git reset --hard ${VERSION} && go mod init)
${TMP_DIR}/generate-groups.sh \
    deepcopy,defaulter \
    kubeception.cloud/kubeception/pkg/apis \
    kubeception.cloud/kubeception/pkg/apis \
    kubeception:v1alpha1 \
    --go-header-file "$DIR"/boilerplate.go.tmpl \
    $@

